### PR TITLE
Allow setting namespace for localStorage keys [close #26] 

### LINKED ISSUE #26: Allow setting namespace for localStorage keys
Will help to avoid key collisions.

```javascript
Vue.use(VueLocalStorage, {
  namespace: 'myProject.'
})

```

### PR DESCRIPTION
**Pull request by nikolay-borzov**
- Add `namespace` property to `VueLocalStorage`;
- Add wrapper around `localStorage.setItem` and `localStorage[key]` in order to modify key;
- Make `build` script portable.
- Add tests

### CODE REVIEW

**Comment by pinguinjkeke** [comment]
Hi! I need to review this a bit, than I'll merge it. Ok?

**Comment by nikolay-borzov** [comment]
Sure!

**Comment by pinguinjkeke** [comment]
@nikolay-borzov  I'm sorry, have been busy for a long time;

**Comment by nikolay-borzov** [comment]
No problem. Thanks!

**Pull request merged**
