### PR TITLE
Update module

### PR DESCRIPTION
**Pull request by yarkovaleksei**
1. Added a universal method for checking type
2. Fix README example

### CODE REVIEW

**Comment by pinguinjkeke** [comment]
Hi!
Why your method is better? Mine is more compact as I see.

**Comment by yarkovaleksei** [comment]
Hi. My project uses your module. When you try to write an object, it is not converted to a string. My method corrects the error.

```javascript
// your module
Vue.localStorage.set('key', {foo: 'bar'}) // In Local Storage result [object Object]
// with my fix
Vue.localStorage.set('key', {foo: 'bar'}) // In Local Storage result {foo: 'bar'}
```

**Comment by pinguinjkeke** [comment]
What version of package are you using?

Check this unit tests, they showing that package perfectly works with Objects.
https://github.com/pinguinjkeke/vue-local-storage/blob/master/tests/unit/vueLocalStorage.test.js#L88

**Comment by yarkovaleksei** [comment]
I use version **0.2.0**.

I do not know why, but it works exactly as I described it.

**Comment by pinguinjkeke** [comment]
So you haven't defined foo variable inside localStorage property in Vue object?
But with your method we can skip variable definition step and make plugin more simplier and intuitive.
In other words, if I apply your PR I should implement other types processing in the same way and drop the localStorage section on Vue instance.

**Comment by yarkovaleksei** [comment]
I use v0.3.0. The problem did not disappear.
- - -





Code snippet
```javascript
import Vue from 'vue'
import VueLocalStorage from 'vue-localstorage'

import constants from '@js/config/constants'

Vue.use(VueLocalStorage)

const localStorage = (store) => {
  const key = constants.SESSION_STORAGE_KEY
  store.subscribe((mutation, payload) => {
    console.log('localStorage:', mutation, payload)
    if (mutation.type === 'setSession') {
      Vue.localStorage.set(key, mutation.payload)
    } else if (mutation.type === 'clearSession') {
      Vue.localStorage.remove(key)
    }
  })
}

export default [
  localStorage
]
```

**Comment by pinguinjkeke** [comment]
Ok, I'll look for it on weekend. But your patch do not solve the problem completely. It should check not only for JSONable, but for other data types (Number, Boolean)

**Comment by yarkovaleksei** [comment]
Yes you are right. My suggestion does not solve the problem. And why not process everything with the help of the function `JSON(stringify/parse)`?

**Comment by pinguinjkeke** [comment]
@yarkovaleksei it sounds good. JSON.parse/stringify will properly work with all datatypes we have.
I'll implement it soon. Unit test also should be rewritten.

**Pull request closed without merging**
