### PR TITLE
remove includes in favor of indexOf

### PR DESCRIPTION
**Pull request by AriLFrankel**
picking up where https://github.com/pinguinjkeke/vue-local-storage/pull/37 leaves off

### CODE REVIEW

**Comment by pinguinjkeke** [comment]
Why polyfill is not an option?

**Comment by AriLFrankel** [comment]
Here are my thoughts:
1) Most importantly, clients of your library don't expect to be signing up for a polyfill of `Array.includes` when they install your library. They might have a competing polyfill implementation, or themselves not be polyfilling Array.includes for some reason of their own.
2) I tend to prefer to do the minimum viable solution. Since this is the only case of using `.includes` in your code base, it feels gratuitous to pull in a polyfill.

What are your thoughts?

**Comment by spotman** [comment]
:+1: for this PR. Forcing a client to use a polyfill for just one line in a third-party lib is a bit strange.

**Comment by AriLFrankel** [comment]
@pinguinjkeke

**Comment by AriLFrankel** [comment]
@pinguinjkeke

**Comment by AriLFrankel** [comment]
@pinguinjkeke

**Comment by AriLFrankel** [comment]
@pinguinjkeke

**Comment by AriLFrankel** [comment]
I guess I'll just close this

**Pull request closed without merging**
